# Site settings
title: Alex Kadis
# email: alex@kadis.me
description: > # this means to ignore newlines until "baseurl:"
  I&rsquo;m an tech project manager, geek, and advocate who is adept at bridging the divide between tech and &ldquo;business&rdquo; teams. I thrive in collaborative spaces.

baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://alexkadis.github.io" # the base hostname & protocol for your site

# baseurl: "/ak2015/_site/" # the subpath of your site, e.g. /blog/
# url: "http://localhost:8888/ak2015/_site/"

twitter_username: alexkadis
github_username: alexkadis
linkedin_username: akadis

# Build settings
markdown: kramdown
krandown:
  parse_block_html: true

# markdown: redcarpet
# redcarpet:
  # extensions: ["strikethrough"]

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: "portfolio"
      type: "pages" # previously `page` in Jekyll 2.2.
    values:
      layout: "portfolio" # overrides previous default layout
      author: "Alex Kadis"
      category: "portfolio"
